### ISSUE TITLE
Failed index download is swallowed, then crashes as `AttributeError: 'Repository' object has no attribute 'addons'`

### ISSUE THREAD

**Issue by ftc2** [xbmc/addon-check#287]
**Version:** 0.0.36 (latest on PyPI). The code is unchanged on `master` (67be5c1).

### Problem

When an official `addons.xml.gz` index fails to download, [`Repository.__init__`](https://github.com/xbmc/addon-check/blob/67be5c1eca23e01402a447f995e2216bd83202f3/kodi_addon_checker/addons/Repository.py#L61-L65) catches the `RequestException` and returns without setting `self.addons`. It doesn't raise or log anything:

```python
try:
    response = self._session.get(path, timeout=(30, 30))
    response.raise_for_status()
except requests.exceptions.RequestException:
    return
```

The run continues until `check_for_existing_addon` evaluates `addon_name in repo`. At that point [`__contains__`](https://github.com/xbmc/addon-check/blob/67be5c1eca23e01402a447f995e2216bd83202f3/kodi_addon_checker/addons/Repository.py#L77-L78) crashes:

```
  File ".../kodi_addon_checker/check_addon.py", line 59, in start
    check_addon_branches.check_for_existing_addon(addon_report, addon, all_repo_addons, args)
  File ".../kodi_addon_checker/check_addon_branches.py", line 50, in check_for_existing_addon
    elif KodiVersion(branch) > kodi_version and addon_name in repo and \
  File ".../kodi_addon_checker/addons/Repository.py", line 78, in __contains__
    for addon in self.addons:
AttributeError: 'Repository' object has no attribute 'addons'
```

### Why it matters

- The error doesn't name the index, the URL, or the cause. It's raised from the add-on checks, so it looks like a checker bug or a problem with the add-on being checked. The real `HTTPError` or `RetryError` is thrown away. This repository's own `test_start` failed this way in #277 while the piers index wasn't online yet, and the traceback gave no hint of that ([comment](https://github.com/xbmc/addon-check/pull/277#issuecomment-2263346276)).
- It happens in ordinary CI. This crash hit 2 of our ~45 GitHub Actions runs, one of them after more than 8 minutes, and the logs couldn't show what had failed. `xbmc/action-kodi-addon-checker` installs this same package.
- The likely trigger is rate limiting. `mirrors.kodi.tv` is rate-limited (#271), and every run requests all ten indexes back to back. In a run we traced locally, the redirector returned 429 (with no `Retry-After`) after about six requests in five seconds, and retry backoff took about 60 of the run's 72 seconds. If one request is refused six times in a row, the adapter gives up after 260 s of backoff (0 + 20 + 40 + 80 + 120), and the resulting `RetryError` is swallowed.

### Reproduce (offline, about a second)

From a checkout of this repository, route the checker through a local "proxy" that returns 404 for every index:

```sh
python -m http.server 8000 &
http_proxy=http://127.0.0.1:8000 kodi-addon-checker --branch omega script.test
```

The output ends with the traceback above. The same server also shows the bug at the unit level: `Repository("piers", "http://127.0.0.1:8000/addons.xml.gz")` returns normally, and `"script.test" in repo` raises the `AttributeError`. That makes a simple regression test.

### Suggested fix

Stop swallowing the exception. Removing the `try`/`except` is enough, because the `requests` error already names the URL and the cause. Alternatively, re-raise it with the branch:

```python
except requests.exceptions.RequestException as exc:
    raise RuntimeError(f"Could not download the {version} add-on index from {path}: {exc}") from exc
```

A failed download still fails the run, which is what [#271 intended](https://github.com/xbmc/addon-check/pull/271#issuecomment-2128316317), but now the error explains why.
